// -*- IDL -*-
/*!
 * @file RTCOutPort.idl
 * @brief InPort interface
 * @date $Date: 2005-05-12 09:06:18 $
 * @author Noriaki Ando <n-ando@aist.go.jp>
 *         Olivier Lemaire
 *
 * << Standard RT-Middleware Interface >>
 *
 * Copyright (C) 2003-2005
 *     Task-intelligence Research Group,
 *     Intelligent Systems Research Institute,
 *     National Institute of
 *         Advanced Industrial Science and Technology (AIST), Japan
 *
 *     Intelligent Mechanism Technology Laboratory,
 *     Technology Fusion Laboratory,
 *     Matsushita Electric Works, Ltd
 *
 *     All rights reserved.
 *
 * $Id: RTCOutPort.idl,v 1.1.1.1 2005-05-12 09:06:18 n-ando Exp $
 *
 */

/*
 * $Log: not supported by cvs2svn $
 *
 */

#ifndef __RTCOutPort_idl__
#define __RTCOutPort_idl__


#include "RTMBase.idl"
#include "RTCInPort.idl"


module RTM {
  
  /*!
   * @if jp
   * @brief SubscriptionType 定義
   * OutPort に対する Subscription 型。OPS は OutPort Subscription を意味する。
   * @else
   * @brief SubscriptionType definition
   * Subscription type to OutPort. OPS stands for OutPort Subscription.
   * @endif
   */
  typedef short SubscriptionType;
  
  
  /*!
   * @if jp
   * @brief 一度だけデータを取得する。
   *
   * データを非同期的に1度だけ取得する。その際クライアントはサーバントが
   * 取得している最中ブロックされない。
   * 最近のデータを取得するのか、最新のデータを取得するのかをオプションで
   * 指定する必要があるかもしれない。
   *
   * @else
   *
   * @brief Subscribe Once.
   *
   * Get only one data asynchronously present, this is to ensure
   * that the client will not block while the servant is acquiring
   * the data (may be we need one more option to specify if we want
   * the data now or the next new data) 
   *
   * @endif
   */
  const SubscriptionType OPS_ONCE = 0;
  
  /*!
   * @if jp
   * @brief 一定周期でデータ送信
   *
   * 指定した周期でデータ送信をサブスクライバに送信する。
   *
   * @else
   *
   * @brief Get data periodic
   *
   * Get data at regular pace
   * @endif
   */
  const SubscriptionType OPS_PERIODIC = 1;
  
  /*!
   * @if jp
   * @brief データ更新時にデータ送信
   *
   * OutPortのデータが更新され次第すぐにサブスクライバにデータが送信される。
   *
   * @else
   *
   * @brief Get data if updated
   *
   * Get data every time a new data is available in outport
   *
   * @endif
   */
  const SubscriptionType OPS_NEW = 2;
  
  /*!
   * @if jp
   * @brief トリガによりデータ送信
   *
   * 予め設定されたトリガによりトリガが発生したときにデータが送信される。
   *
   * @else
   *
   * @brief Get data if triggered
   *
   * Get data every time a condition is reached (like "is > 2.0",
   * we need to define a condition definition language but it's
   * not yet urgent)
   *
   * @endif
   */
  const SubscriptionType OPS_TRIGGERED = 3;
  
  /*!
   * @if jp
   * @brief 一定周期でデータ更新時のみ送信
   *
   * データ更新時のみ、予め設定された周期のタイミングでデータが送信される。
   * 周期がΔt [s] に設定されたとき、データ送信のタイミングは、データが
   * 更新されてから最も近い nΔt [s] に行われる。
   *
   * @else
   *
   * @brief Get data periodic if updated
   *
   * Get data at regular pace only if a new data is available
   * in the outport : especially useful for analog data :
   * client leads synchro
   *
   * @endif
   */
  const SubscriptionType OSP_PERIODIC_NEW = 4;
  
  /*!
   * @if jp
   * @brief データ更新時に送信・一定周期で送信
   *
   * データ更新時にすぐにデータは送信されるが、それ以降はデータが更新され
   * 続ける限りは一定周期で送信で送信される。
   *
   * @else
   *
   * @brief Get data if updated and periodic
   *
   * Get data every time a new data is available in outport
   * but not faster than a given pace : server leads synchro
   *
   * @endif
   */
  const SubscriptionType OPS_NEW_PERIODIC = 5;
  
  /*!
   * @if jp
   * @brief 一定周期でトリガ時のみ送信
   *
   * OPS_PERIODIC_NEW の送信条件がトリガに変わるだけで、そのほかの動作は
   * OPS_PERIODIC_NEW と同じになる。
   *
   * @else
   *
   * @brief Get data periodic if triggerd
   *
   * Same as OSP_PERIODIC_NEW but the "new" condition is
   * replaced by the "trigger" condition
   *
   * @endif
   */
  const SubscriptionType OPS_PERIODIC_TRIGGERED = 6;
  
  /*!
   * @if jp
   * @brief トリガ時に送信・一定周期で送信
   *
   * OPS_TRIGGERRED_PERIODIC の送信条件がトリガに変わるだけで、そのほかの動作は
   * OPS_TRIGGERRED_PERIODIC と同じになる。
   *
   * @else
   *
   * @brief Get data if triggered and periodic
   *
   * Same as OSP_TRIGGERED_PERIODIC but the "new" condition
   * is replaced by the "trigger" condition
   *
   * @endif
   */
  const SubscriptionType OPS_TRIGGERRED_PERIODIC = 7;
  
  
  /*!
   * @if jp
   * @brief SubscriberProfile
   *
   * サブスクライブに関するサブスクライバのプロファイルを定義。
   *
   * @else
   *
   * @brief SubscriberProfile
   *
   * Structure definition of subscriber profile.
   *
   * @endif
   */
  struct SubscriberProfile
  {
	/*!
	 * @if jp
	 * @brief サブスクライブ型
	 *
	 * サブスクライブに関するサブスクライバのプロファイルを定義。
	 * OPS_ONCE OPS_PERIODIC OPS_NEW OPS_TRIGGERED OSP_PERIODIC_NEW
	 * OPS_NEW_PERIODIC OPS_PERIODIC_TRIGGERED OPS_TRIGGERRED_PERIODIC
	 * のいずれかを指定。
	 *
	 * @else
	 *
	 * @brief SubscriberProfile
	 *
	 * Structure definition of subscriber profile.
	 * Set one of the following subscription type.
	 * OPS_ONCE OPS_PERIODIC OPS_NEW OPS_TRIGGERED OSP_PERIODIC_NEW
	 * OPS_NEW_PERIODIC OPS_PERIODIC_TRIGGERED OPS_TRIGGERRED_PERIODIC
	 *
	 * @endif
	 */
	SubscriptionType subscription_type;
	
	/*!
	 * @if jp
	 * @brief イベント型サブスクライブフラグ
	 * @else
	 * @brief Flag of event type eubscription
	 * @endif
	 */
	boolean event_base;
	
	/*!
	 * @if jp
	 * @brief サブスクライブプロパティ
	 * @else
	 * @brief Subscriber properties
	 * @endif
	 */
	
	NVList properties;
  };
  
  
  /*!
   * @if jp
   *
   * @class OutPort
   *
   * @brief OutPort インターフェース
   * 
   * OutPort のインターフェースを定義。
   *
   * @else
   *
   * @class OutPort
   *
   * @brief Output interface 
   *
   * Definition of interface of OutPort.
   *
   * @endif
   */
  interface OutPort
  {
	/*!
	 * @if jp
	 * @brief OutPort の値をAny型で取得
	 * @else
	 * @brief Get data of Output as Any type value
	 * @endif
	 */
    any get();
	
	/*!
	 * @if jp
	 * @brief OutPort をサブスクライブする
	 * @else
	 * @brief Subscribe this OutPort
	 * @endif
	 */
    RtmRes subscribe(in InPort in_port, out SubscriptionID id,
					 in SubscriberProfile profile);
	
	/*!
	 * @if jp
	 * @brief OutPort をアンサブスクライブする
	 * @else
	 * @brief Unsubscribe this OutPort
	 * @endif
	 */
    RtmRes unsubscribe(in SubscriptionID id);
	
	/*!
	 * @if jp
	 * @brief OutPort をサブスクライブしているInPortのリスト
	 * @else
	 * @brief Subscribing InPorts list
	 * @endif
	 */
    readonly attribute InPortList inports;
	
	/*!
	 * @if jp
	 * @brief OutPort のプロファイル
	 * @else
	 * @brief OutPort profile
	 * @endif
	 */
	readonly attribute PortProfile profile;
  };
  
  /*!
   * @if jp
   * @brief OutPort のリスト
   * @else
   * @brief OutPort list
   * @endif
   */
  typedef sequence<OutPort> OutPortList;
  
  
}; // end of module RTM

#endif // __RTCOutPort_idl__

