//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: CORBACdrData.cpp
//  Source: CORBACdrData.idl
//  Generated: Wed Mar 27 20:28:43 2019
//  OpenSplice 6.9.190227OSS
//  
//******************************************************************

#include "CORBACdrData.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::Octet, struct _data_seq_uniq_>;
#endif



