//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: CORBACdrData.h
//  Source: CORBACdrData.idl
//  Generated: Wed Mar 27 20:28:43 2019
//  OpenSplice 6.9.190227OSS
//  
//******************************************************************
#ifndef OPENSPLICE_CORBACDRDATA_H_
#define OPENSPLICE_CORBACDRDATA_H_

#include "sacpp_mapping.h"


namespace OpenRTM_OpenSplice
{
   struct CORBACdrData;

   struct CORBACdrData
   {
         struct _data_seq_uniq_ {};
         using _data_seq = DDS_DCPSUFLSeq < DDS::Octet, struct _data_seq_uniq_>;
         using _data_seq_var = DDS_DCPSSequence_var < _data_seq>;
         using _data_seq_out = DDS_DCPSSequence_out < _data_seq>;
         _data_seq data;
   };

   using CORBACdrData_var = DDS_DCPSStruct_var < CORBACdrData>;
   using CORBACdrData_out = DDS_DCPSStruct_out < CORBACdrData>;
}




#endif
