//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: CORBACdrData.cpp
//  Source: CORBACdrData.idl
//  Generated: Wed Mar 27 20:28:43 2019
//  OpenSplice 6.9.190227OSS
//  
//******************************************************************

#if defined(WIN32) || defined(_WIN32) || defined(__WIN32__) || defined(__NT__)
#pragma warning(push)
#pragma warning(disable:4819)
#endif
#include "CORBACdrData.h"
#if defined(WIN32) || defined(_WIN32) || defined(__WIN32__) || defined(__NT__)
#pragma warning(pop)
#endif

#ifdef DDS_USE_EXPLICIT_TEMPLATES
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::Octet, struct _data_seq_uniq_>;
#endif
#endif



