//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: CORBACdrData.h
//  Source: CORBACdrData.idl
//  Generated: Wed Mar 27 20:28:43 2019
//  OpenSplice 6.9.190227OSS
//  
//******************************************************************
#ifndef _CORBACDRDATA_H_
#define _CORBACDRDATA_H_

#include "sacpp_mapping.h"


namespace OpenRTM
{
   struct CORBACdrData;

   struct CORBACdrData
   {
         struct _data_seq_uniq_ {};
         typedef DDS_DCPSUFLSeq < DDS::Octet, struct _data_seq_uniq_> _data_seq;
         typedef DDS_DCPSSequence_var < _data_seq> _data_seq_var;
         typedef DDS_DCPSSequence_out < _data_seq> _data_seq_out;
         _data_seq data;
   };

   typedef DDS_DCPSStruct_var < CORBACdrData> CORBACdrData_var;
   typedef DDS_DCPSStruct_out < CORBACdrData> CORBACdrData_out;
}




#endif
