// This header file is automatically generated.
// Do not edit this file.

const char* openrtm_name    = "OpenRTM-aist-1.1.2";
const char* openrtm_version = "1.1.2";
const char* corba_name      = "omniORB";
