// -*- IDL -*-
/*!
 * @file RTCInPort.idl
 * @brief InPort interface
 * @date $Date: 2005-05-27 07:40:46 $
 * @author Noriaki Ando <n-ando@aist.go.jp>
 *         Olivier Lemaire
 *
 * << Standard RT-Middleware Interface >>
 *
 * Copyright (C) 2003-2005
 *     Task-intelligence Research Group,
 *     Intelligent Systems Research Institute,
 *     National Institute of
 *         Advanced Industrial Science and Technology (AIST), Japan
 *
 *     Intelligent Mechanism Technology Laboratory,
 *     Technology Fusion Laboratory,
 *     Matsushita Electric Works, Ltd
 *
 *     All rights reserved.
 *
 * $Id: RTCInPort.idl,v 1.2 2005-05-27 07:40:46 n-ando Exp $
 *
 */

/*
 * $Log: not supported by cvs2svn $
 * Revision 1.1.1.1  2005/05/12 09:06:18  n-ando
 * Public release.
 *
 *
 */

#ifndef __RTCInPort_idl__
#define __RTCInPort_idl__


#include "RTMBase.idl"
#include "RTCPortBase.idl"

module RTM {
 
  /*!
   * @if jp
   *
   * @class InPort
   *
   * @brief InPort インターフェース
   * 
   * InPort のインターフェース定義。
   * Any型でのデータの入力を受け付ける。
   *
   * @else
   *
   * @class InPort
   *
   * @brief Input port interface.
   *
   * @endif
   */
  interface InPort
	: PortBase
  {
	/*!
	 * @if jp
	 * @brief InPort に値を渡す
	 * @else
	 * @brief Put data on InPort
	 * @endif
	 */
    void put(in any data) raises(Disconnected);
  };
  
  /*!
   * @if jp
   * @brief InPort のリスト
   * @else
   * @brief InPort list
   * @endif
   */
  typedef sequence<InPort> InPortList;
  
}; // end of module RTM

#endif // __RTCInPort_idl__

