// -*- IDL -*-
/*!
 * @file OpenRTM.idl
 * @brief OpenRTM interface definition
 * @date $Date: 2007-04-13 18:17:59 $
 * @author Noriaki Ando <n-ando@aist.go.jp>
 *
 * Copyright (C) 2007
 *     Task-intelligence Research Group,
 *     Intelligent Systems Research Institute,
 *     National Institute of
 *         Advanced Industrial Science and Technology (AIST), Japan
 *     All rights reserved.
 *
 * $Id: OpenRTM.idl,v 1.1 2007-04-13 18:17:59 n-ando Exp $
 *
 */

/*
 * $Log: not supported by cvs2svn $
 */

#include "RTC.idl"

#pragma prefix "openrtm.aist.go.jp"

module RTC
{

  interface DataFlowComponent
    : RTObject, DataFlowParticipant
  {
  };

  interface FiniteStateMachineComponent
    : RTObject, FsmParticipant
  {
  };

  interface DataFlowFiniteStateMachineComponent
    : RTObject, DataFlowParticipant, FsmParticipant
  {
  };

  interface DataFlowMultiModeComponent
    : RTObject, DataFlowParticipant, MultiModeObject
  {
  };

  interface FiniteStateMachineMultiModeComponent
    : RTObject, FsmParticipant, MultiModeObject
  {
  };

  interface DataFlowFiniteStateMachineMultiModeComponent
    : RTObject, DataFlowParticipant, FsmParticipant, MultiModeObject
  {
  };


  interface ExtTrigExecutionContextService
    : ExecutionContextService
  {
    oneway void tick();
  };

};
