#!/usr/bin/env python
# -*- coding: shift_jis -*-
# -*- python -*-
#
#  @file template.py
#  @brief doil interface header template
#  @date $Date$
#  @author Noriaki Ando <n-ando@aist.go.jp>
# 
#  Copyright (C) 2008
#      Task-intelligence Research Group,
#      Intelligent Systems Research Institute,
#      National Institute of
#          Advanced Industrial Science and Technology (AIST), Japan
#      All rights reserved.
# 
#  $Id$
# 

interface_h = """\
// -*- C++ -*-
/*!
 * @file [iface_h] 
 * @brief [servant_name] C++ interface definition for doil
 * @date $Date$
 * @author This file was automatically generated by omniidl/doil backend
 *
 * $Id$
 */

#ifndef [iface_include_guard] 
#define [iface_include_guard] 

[for inc in include_h]
#include <[inc]>
[endfor]

[for ns in iface_ns]
namespace [ns] 
{
[endfor]
  /*!
   * @if jp
   * @class [iface_name] 
   * @brief [iface_name] インターフェースクラス
   * @else
   * @class [iface_name] 
   * @brief [iface_name] interface class
   * @endif
   */
  class [iface_name] 
  {
  public:
    virtual ~[iface_name]();

[for op in operations]
    virtual [op.return.local.ret_type]
[op.name]([for a in op.args]
[if-index a is last][a.local.arg_type] [a.local.arg_name]
[else][a.local.arg_type] [a.local.arg_name], [endif]
[endfor]);
[endfor]

  };
[for ns in iface_ns]
}; // namespace [ns] 
[endfor]

#endif // [iface_include_guard]
"""
